import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import AppDataProvider from "@/context";
// import 'chart.js/auto';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AppDataProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="w-full h-screen flex items-center justify-center text-center lg:hidden animate-pulse">
              Please open it on laptop or desktop
            </div>
            <div className="hidden lg:flex">{children}</div>
          </ThemeProvider>
        </AppDataProvider>
      </body>
    </html>
  );
}
